### ISSUE TITLE
add me on discord for a rootkit malware : antianalysis

### ISSUE THREAD

**Issue by 0xSuspect** [fuckedd/Myths-Grabber#7]
gui.exe its a paylod binded with a grabber lol

**Comment by bylldgo** [comment]
you even dont know C++ what you mean by rootkit

**Comment by 0xSuspect** [comment]
lol you dont know what is rootkit

**Comment by 0xSuspect** [comment]
+ if you put the gui.exe in to the dnspy its orginal name is Output thats meen's its a xworm paylod binded with something els

**Comment by 0xSuspect** [comment]
![image](https://github.com/fuckedd/Myths-Grabber/assets/152611711/4be65a32-0940-45ee-b6e6-25ec10925705)
lol :-)

**Comment by bylldgo** [comment]
so its not rootkit

**Comment by 0xSuspect** [comment]
No , I mean if he want's a rootkit paylod that no one one can see what it is fully encrypted

**Comment by bylldgo** [comment]
Ok Ok i understand

**Comment by 0xSuspect** [comment]
lol
thats why u r a motherfucker

**Comment by EvilBytecode** [comment]
💀
